language: node_js

node_js: 10

os: osx

cache:
  directories:
    - node_modules

addons:
  chrome: beta

before_install:
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
  â‹®

install: npm ci
